### ISSUE TITLE
Searching with the userscript makes the page lag

### ISSUE THREAD

**Issue by CrocodileCroco** [Smrman/Scratch-Forum-UserScript#1]
When i search with the userscript activated , it makes the page lag

**Comment by Ascor8522** [comment]
What do you mean with "lag"?
Does the page keep loading until the tab does not respond anymore?

**Comment by Ascor8522** [comment]
Ok, I think I solved the problem.
Could you please close your browser and open it again and search something in the searchbar to see if it still haeppens....

**Comment by CrocodileCroco** [comment]
Now it doesn't lag anymore ! :) Thank you !

**Comment by Ascor8522** [comment]
You're welcome.
Thanks for reporting the bug ;)
